name=TinyFATFS
version=0.3.0
author=phil schatzmann
maintainer=phil schatzmann
sentence=FAT file system (developped by ChaN)
paragraph=FAT file system (developped by ChaN)
category=Data Storage
url=https://github.com/pschatzmann/TinyFATFS
architectures=*
license=MIT
